Refine test workflow to improve business rule validation for Windows and Unix-like systems. This update adjusts the file path checks for the business rule artifact based on the operating system, ensuring accurate error handling and compatibility across environments.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -185,12 +185,13 @@ jobs:
 
           # Set a business rule that will be passed (Linux only)
           # Needs to be passed into the root environment
-          echo "Setting business rule so that it will be passed and leave an artifact in $HOME/passed_business_rule"
           if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "macos-latest" ]]; then
+            echo "Setting business rule so that it will be passed and leave an artifact in $HOME/passed_business_rule"
             export EDAMAME_BUSINESS_RULES_CMD="{ echo passed > $HOME/passed_business_rule; } > /dev/null 2>&1"
           else 
             if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
               # Use PowerShell
+              echo "Setting business rule so that it will be passed and leave an artifact in $USERPROFILE/passed_business_rule"
               export EDAMAME_BUSINESS_RULES_CMD="Write-Output 'passed' > \"$env:USERPROFILE/passed_business_rule\" 2>NUL"
             else
               echo "Error: Unsupported OS"
@@ -203,9 +204,15 @@ jobs:
           $SUDO_CMD ~/$BINARY -v score
 
           # Check if the business rule was passed
-          if [[ ! -f $HOME/passed_business_rule ]]; then
-            echo "Error: Business rule not passed"
-            exit 1
+          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+            if [[ ! -f $USERPROFILE/passed_business_rule ]]; then
+              echo "Error: Business rule not passed"
+              exit 1
+            fi
+          else
+            if [[ ! -f $HOME/passed_business_rule ]]; then
+              echo "Error: Business rule not passed"
+              exit 1
           fi
           
           # Test remediate command with skip_remediations
