Refine test workflow to improve OS-specific command handling. This update corrects the conditional logic for setting the EDAMAME_BUSINESS_RULES_CMD variable, adding error handling for unsupported operating systems and ensuring proper execution across different environments.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -188,9 +188,14 @@ jobs:
           echo "Setting business rule so that it will be passed and leave an artifact in $HOME/passed_business_rule"
           if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "macos-latest" ]]; then
             export EDAMAME_BUSINESS_RULES_CMD="{ echo passed > $HOME/passed_business_rule; } > /dev/null 2>&1"
-          else if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
-            # Use PowerShell
-            export EDAMAME_BUSINESS_RULES_CMD="{ Write-Output 'passed' > `$HOME/passed_business_rule } > `$null 2>&1"
+          else 
+            if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+              # Use PowerShell
+              export EDAMAME_BUSINESS_RULES_CMD="{ Write-Output 'passed' > `$HOME/passed_business_rule } > `$null 2>&1"
+            else
+              echo "Error: Unsupported OS"
+              exit 1
+            fi
           fi
           
           # Perform a simple score computation
